---
  ###########################################################
  #           Playbook to query NXOSv switches             #
  ###########################################################
  - name: Retrieve facts from NXOSv switches
    hosts: nxosv-switches
    connection: local

    tasks:
      - name: "Retrieving NXOS facts."
        nxos_facts:
          host: "{{inventory_hostname}}"
          transport: nxapi
        register: nxos_info

      - name: run show ospf process on remote devices
        nxos_command:
          commands: "show ip ospf | i Process"
        register: nxos_show_ospf_process

      - name: run show vlan on remote devices
        nxos_command:
          commands: show vlan
        register: nxos_show_vlan

      - name: "Hi! Here are my facts."
        debug: msg="{{nxos_info}}"

      - name: "NXOSv show ospf process"
        debug: msg="{{nxos_show_ospf_process}}"

      - name: "NXOSv show vlan"
        debug: msg="{{nxos_show_vlan}}"
