---
  ###########################################################
  #           Playbook to query NXOSv switches             #
  ###########################################################
  - name: Retrieve facts from NXOSv switches
    hosts: nxosv-switches
    connection: local

    tasks:
      - name: "Retrieving NXOS facts."
        nxos_facts:
          host: "{{inventory_hostname}}"
          transport: nxapi
        register: nxos_info

      - name: "Hi! Here are my facts."
        debug: msg="{{nxos_info}}"
