---
  ###########################################################
  #         Playbook to configure dCloud switches           #
  ###########################################################
  - name: Configuring NXOSv switches
    hosts: nxosv-switches
    connection: local

    tasks:
      - name: "Create device configurations from templates."
        template:
          src: "{{template}}"
          dest: "./{{inventory_hostname}}.conf"

      - debug: msg="./{{config}}"
      - name: "Configuring NXOS stuff."
        nxos_config:
          src: "./{{config}}"
          provider:
            host: "{{inventory_hostname}}"
            transport: nxapi
